language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly
env:
  - PREFER_LOWEST="--prefer-lowest --prefer-stable"
  - PREFER_LOWEST=""
services:
  - memcached
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
before_script:
  - pecl install memcache
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer update $PREFER_LOWEST
script:
  - ./vendor/bin/phpunit --coverage-clover clover.xml
after_success: ./vendor/bin/coveralls -v
